// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC58hvuNFU5bBEmRKDZScQa8JBZ9ZUaNPY',
    appId: '1:840431394393:web:8ad3ae86e8880f70445b48',
    messagingSenderId: '840431394393',
    projectId: 'babytracker-af417',
    authDomain: 'babytracker-af417.firebaseapp.com',
    storageBucket: 'babytracker-af417.appspot.com',
    measurementId: 'G-3GGZTSHZYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxXP4wbyE1x0wm05MDxYhMxbAP6Y4PJ-Y',
    appId: '1:840431394393:android:717ef4dff3164b0a445b48',
    messagingSenderId: '840431394393',
    projectId: 'babytracker-af417',
    storageBucket: 'babytracker-af417.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGgFzTMufPyVeTZi1ib7fAlGC3jwid4IY',
    appId: '1:840431394393:ios:78509356c90b7fad445b48',
    messagingSenderId: '840431394393',
    projectId: 'babytracker-af417',
    storageBucket: 'babytracker-af417.appspot.com',
    iosClientId: '840431394393-daqedrfuv1sse6kn9mt0k0rdt2po0ckg.apps.googleusercontent.com',
    iosBundleId: 'au.edu.utas.kit305.babytracker.babyTracker',
  );
}
